backend:
  name: github
  repo: decidim/decidim.org
  branch: content/update

media_folder: "source/blog/images"

collections:
  - name: "post-en"
    label: "Post (EN)"
    folder: "source/blog/en"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post-es"
    label: "Post (ES)"
    folder: "source/blog/hu"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Draft", name: "published", widget: "hidden", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "FAQs"
    name: "faqs"
    create: true
    files:
      - label: "FAQ questions"
        name: "faqs"
        file: "data/faqs.yml"
        fields:
          - label: EN
            name: en
            widget: list
            fields:
              - {label: question, name: question, widget: string}
              - {label: answer, name: answer, widget: string}
          - label: HU
            name: hu
            widget: list
            fields:
              - {label: question, name: question, widget: string}
              - {label: answer, name: answer, widget: string}
