backend:
  name: github
  repo: decidim/decidim.org
  branch: master

media_folder: "source/blog/images"

collections:
  - name: "post"
    label: "Post"
    folder: "source/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
